apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: energyvision
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: test
  components:
    - name: web
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-global:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          resources:
            requests:
              memory: '512Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '2000m'
          imageTagName: main-latest
          variables:
            BRANDMASTER_EMAIL_AUTHENTICATION_URL: 'https://stage.brandmaster.com/apigateway/apigateway.dll/SOAP_UNENCRYPTED?service=Authentication'
            BRANDMASTER_EMAIL_SUBSCRIPTION_URL: 'https://stage.brandmaster.com/apigateway/apigateway.dll/SOAP_UNENCRYPTED?service=Subscription'
            
      variables:
        BRANDMASTER_EMAIL_APN_ID: '32'
        BRANDMASTER_EMAIL_OTY_ID: '114961'
        BRANDMASTER_EMAIL_PTL_ID: '14414'
        NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: 'testStringID'
      secrets:
        - BRANDMASTER_EMAIL_CLIENT_SECRET
        - BRANDMASTER_EMAIL_PASSWORD

    - name: web-brazil
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-brazil:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-germany
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-germany:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-argentina
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-argentina:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-global-development
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-global-development:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest
          
           

    - name: web-poland
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-poland:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-equinorfunds
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-equinorfunds:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-japan
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-japan:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-storage
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-storage:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-loop
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-loop:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-techstars
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-techstars:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-southkorea
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-southkorea:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: web-typography
      publicPort: http
      image: ghcr.io/equinor/energyvision/web-global-development:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-brazil
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-brazil:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-germany
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-germany:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-argentina
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-argentina:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-global-development
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-global-development:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-poland
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-poland:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-japan
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-japan:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-storage
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-storage:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-techstars
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-techstars:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-equinorfunds
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-equinorfunds:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-loop
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-loop:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

    - name: studio-southkorea
      publicPort: http
      image: ghcr.io/equinor/energyvision/studio-southkorea:{imageTagName}
      alwaysPullImageOnDeploy: true
      ports:
        - name: http
          port: 3333
      environmentConfig:
        - environment: dev
          imageTagName: main-latest

  dnsAppAlias:
    environment: dev
    component: web
  privateImageHubs:
    ghcr.io:
      username: nilsml
      email: nilsml@nilsland.com
