name: 'Update radixconfig'
description: 'Update radixconfig.yaml with certain tag'
inputs:
  PAT:
    description: 'Private access token'
    required: true
  component:
    description: 'web or studio'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout ğŸ›ï¸
      id: checkout
      uses: actions/checkout@v3
    - name: Set image tag ğŸ·
      shell: bash
      id: set-default-image-tag
      run: |
        echo "IMAGE_TAG_SHA=$(git rev-parse --short ${GITHUB_SHA})" >> $GITHUB_ENV
    - name: Checkout internal ğŸ›ï¸
      id: checkout-internal
      uses: actions/checkout@v3
      with:
        repository: 'equinor/energyvision-internal'
        ref: main
        token: ${{ inputs.PAT }} # Replace with ssh as per https://stackoverflow.com/questions/60222741/github-actions-and-git-clone-issue
    - name: Modify radixconfig tag for preprod on main branch ğŸ—’ï¸
      if: github.ref == 'refs/heads/main'
      shell: bash
      id: modify-radix
      run: |
        # Install pre-requisite
        python -m pip install --user ruamel.yaml
        python ci/upgradePreprod.py ${{ inputs.component }} ${{ env.IMAGE_TAG_SHA }}
        git config --global user.name 'github'
        git config --global user.email 'nilsml@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ inputs.PAT }}@github.com/equinor/energyvision-internal
        git commit -am ${{ env.IMAGE_TAG_SHA }}
        git pull --rebase origin main
        git push origin HEAD:main
    - name: log-errors-to-slack ğŸ“„
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: failure()

