name: Upload storybook to Azure blob storage
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/components/**'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies ğŸ”½
        run: |
          yarn install --prefer-offline
          yarn --cwd ./web/ install --prefer-offline
      - name: Lint components ğŸ”
        run: |
          yarn eslint './web/components/**/*.{ts,tsx}'
      - name: Run tests ğŸ•µï¸â€â™€ï¸
        run: |
          yarn --cwd ./web/ run test ./components/
      - name: Build storybook ğŸ”§
        run: |
          yarn --cwd ./web/ build-storybook
      - name: Deploy ğŸš€
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: './web/storybook-static'
          container_name: '$web'
          connection_string: ${{ secrets.AZ_CONNECTION_STRING }}
          sync: true
