name: Build & deploy Storybook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/components/**'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Cache pnpm modules ğŸ’¾
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - name: Install pnpm ğŸ“¦
        uses: pnpm/actions-setup@v1.2.1
        with:
          version: latest
      - name: Install dependencies ğŸ”½
        run: |
          pnpm install
          pnpm install --filter energy-vision-web
      - name: Lint components ğŸ”
        run: |
          pnpm lint:components
      - name: Run tests ğŸ•µï¸â€â™€ï¸
        run: |
          pnpm test ./components/ --filter energy-vision-web
      - name: Build storybook ğŸ”§
        run: |
          pnpm build-storybook --filter energy-vision-web
      - name: Deploy ğŸš€
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: './web/storybook-static'
          container_name: '$web'
          connection_string: ${{ secrets.AZ_CONNECTION_STRING }}
          sync: true
