name: Upload storybook to Azure blob storage
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/components/**'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install dependencies ğŸ”½
        run: |
          yarn install
          yarn --cwd ./web/ install
      - name: Lint components ğŸ”
        run: |
          yarn eslint './web/components/**/*.{ts,tsx}'
      - name: Build storybook ğŸ”§
        run: |
          yarn --cwd ./web/ build-storybook
      - name: Deploy ğŸš€
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: './web/storybook-static'
          container_name: '$web'
          connection_string: ${{ secrets.AZ_CONNECTION_STRING }}
          sync: true
