name: 'Test workflow for setting up project workflows'
on:
  workflow_dispatch:

jobs:
  get-list:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: 'Get list'
        id: 'get-list'
        uses: ./.github/workflows/project/
