name: 'Test workflow for setting up project workflows'
on:
  workflow_dispatch:

jobs:
  get-list:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3

      - name: 'Get list'
        id: 'get-list'
        with:
          token: ${{ secrets.PADMS_PAT_READ_PACKAGE }}
          slack_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: ./.github/workflows/project/
